# Generated by Django 5.1.2 on 2024-11-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_commission_percentage_order_coupon_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_id',
        ),
    ]
