# Generated by Django 4.2 on 2024-11-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.platform'),
        ),
    ]
